name: Build

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ["17"]

    steps:

    - uses: actions/checkout@v3

    - name: Use Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - run: mvn package
