name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish_to_github_packages:
        description: "Publish to GitHub Packages"
        required: true
        type: boolean

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ["17"]

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - run: mvn package

  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_to_github_packages }}
    needs: tests
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
